services:
  app:
    container_name: pyramid_app
    build: .
    ports:
      - "6543:6543"
    depends_on:
      - db_loader

  db_loader:
    image: postgres
    container_name: loadSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: WorkQ123
      POSTGRES_DB: workq
    ports:
      - "5432:5432"