def includeme(config):
    config.add_static_view('static', 'static')
    config.add_route('home', '/')
    config.add_route('startpage','/start')
    config.add_route('sign_in', '/sign-in')
    config.add_route('logout', '/logout')
    config.add_route('sign_up', '/sign-up')
    config.add_route('edit_user', '/edit_user')
    config.add_route('update_user', '/update_user')
    config.add_route('pm_main', '/pm_main')
    config.add_route('add_task', '/add_task')
    config.add_route('info_user', '/info_user')
    config.add_route('add_user', '/add_user')
    config.add_route('task_view', '/task_view')
    config.add_route('set_active_project', '/set_active_project')
    config.add_route('request_management', '/request_management')
    config.add_route('submit_request', '/submit-request')
    config.add_route('handle_request_action', '/handle-request-action')
