name: Execute expired tasks daily

on:
  schedule:
    - cron: '0 2 * * *'  # Todos los días a las 2:00 AM UTC
  workflow_dispatch:     # Permite ejecutarlo manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python update_expired_tasks.py
